[package]
name = "librustodoro"
version = "0.1.0"
authors = ["Hernawan Fa'iz Abdillah <hernawan.faiz@abdillah.me>"]

[dependencies]
libc = "0.2.42"
serde_json = "1.0"

[lib]
name = "rustodoro"
crate-type = ["rlib", "dylib"]
